language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
- '5.7'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: ZHZ5Of1MDjf0sCFtUlv9OKioh1U9Fh7JjqgiEtm+FWBb1kwDMkDM+xd+78YUOipgPfk7OxIVAW4tOrKk3UmWMySpw4/BbzB+MB3oCnIcqzk+yBPbTctG17CLxp+6oN/v/5+KmLCjf26wlt5QK5HDD2CtoyE5iITbSuUtRxCUaUWwUsNj8Ccu2Cz5cK2mXfrZRCCL+KJbQexffkkbzSNMjn4s+yDJyVTK9Oy+QnIAzPDeohvbmbDRdQmWyF95lRk5RbBi89zcJckSwmfISN8PTg4Qq+4zNn6aF5w3BAbyNH37lNb2hiqCrkHdUykgFF/J+hwEWva4eNmRzzVgq8b1xft3D1VeSGKMehK/3gnu8XmPlROOGnA1Z2Pbm7ui19npT04bOfihltliXvZFYVCY9k8tnmubJzBvwf3U425ESgkUGWD7C1rT+E4W/ue36nRTnKFQ6RPbkqI+CJ1Hey4djE8ZWPBwAFlUoT2Wxn0Yx5wMFIpTnJXKyvZXdQ3cgeMFQIsY867tzro04DvM/N37PqroUpqAyYTRKLxAV+H5ifJoA60wZqXOULmXob+lxp0zLVyCESu85j0gbH0aqF630PZNtfptPGP9o3x87xCy5qihoYFvf38ALGTJ6mIQqBzFQaM0+eUPRTqn2z6O8kPcKCoIwqUNWoIuHzx0IWaN2+Y=
  app: OneCore
  on:
    repo: dzzdzzdz/OneCore
