language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
- '5.7'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: oBhsEAjYzXUhRAINXlrUHfCfes8oAhgV8fMM04QksbWRyq4u+V3Mq753Vd+rs8s62aHQmVsIhLJ1ONQBluGCsEiARq4ARqhJY6NvMZMwZNfxKOhGklaRhaHF6h1isXfkHdZgLr6OCtix3yXfnt76TXrGlrYIaL2W8bfEJ+hbhJoSI6pOIuQkkEDJ+sNxRtmkmOSMEwBckqaMTS6cLJ1im8my8O922umRixAEO3RdA0+0NIllZOIZHGTirxnRGAzs8JM8OHCk6/iGN5gYssRTczYuB2YhpiST7gl0PT427LUbtw9x9k4wTzwNrf9lIBT+PRPtczKwr7skicbOBFndWyVV9J3xc6k3jwHIWREQSWRAvvXuxDHTL5wkdM0kgqOEstVM2lqZV788m9AWNX30lzB9Q8DIZ4QieYR9flqEn5feCw0ig0gPeES3XE7KDfPUrok/sYfOpY/Cop6McDzDWxgtvwX37NO4mAEAR/I2ZKyhv0U1d2q3Z6cGP/yYhtntJAnQAfQDZoxS7gXVeb4Ce4jhAFvZlMHKv/9zRZJ1iSLBJuP4W970+Nz+taX9GxIghZrdPn9OFX1AqZSV57MOgwuCDepyAbHG7lAGoNEZxHliaiT+5+yu3szUJ+QWW2y9RfTfN20Od271fK4EHyGZWBqcsRtZs6MiwKzCw0Uj4GI=
  app: OneCore
