language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
- '5.7'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: gHfHGIielQdPQWj+1O6+o9iGmSvBMz0QayGcfiWYeSO4PeQnhhYEwsUgy79eVgjxHGEZqr2qwrIaNYOFbDEVhzAR9FT4zSvJRZYUvRCCJYq192bi/gYS8zzTIJ0y2cf+ci94REoF7qQ5SGPMvYymMBCV12BIbXeC+3k6JXN0P7h6t6Ae8DLEOrZ+eT4XR1862YprhK0SFbZMzMzyTEgnrZI93x03H3VWIrDhX/0eEde60wSjJvahuVjJ8hvLBowwDStdpkeB7zQCk2tgwNFIj70SaMuL8PjV7R9lqCLx350Wl6/Oay8/2f+H2PXX1boo+XYq/arYKJyN4ymvuwqtQyuJjeajqSBPME8dhfpGkeUWxWtj5U1L0xxFiBaO0+c5Y8tARJk6dSJh7wOl0fICRx9kfPpCafn9xxq7yJLmbXQN8Di94w7Zdk7LEPja4k9UWbPnxEtNjxbxzs13s4D0D/4FNkiynN9IbjPjlxEam5VN7a+BybLvbQTckBzGkgtKaU9HcfCkzI6bNrI76i8mqfkVovDrsYG9pl4OjGV/IKwHSyeVjvO5LalVS92UTpQrC/szhBKEf5WAp+787y4/L4rHKtI2+HGJBHQuEb4ZqiipCXG8rYq4NWMn8mSzPdpZI1ne6Z9LrXUhgaaVO4mCEq16Bn9FpR9oXayefAvS2Jo=
  app: onecare
